### PR TITLE
Update discord plugin

### PR DESCRIPTION
**Pull request by hbiede**

### CODE REVIEW

**Comment by vaindil** [comment]
I have not looked at this code in years. What's the problem being fixed? Was it fixed upstream in [hangoutsbot/hangoutsbot](https://github.com/hangoutsbot/hangoutsbot)? (Just trying to get info for when I test it.)

**Comment by hbiede** [comment]
The bot was echoing (You send a message in Discord and the bot would relay it back and forth 2-4 times back into the Discord channel. This update has been working for the last few weeks without any hiccups

**Comment by hbiede** [comment]
And then some minor improvements to log

**Comment by vaindil** [comment]
Is that everything you wanted in the PR? I can test it if that's the case.

**Comment by hbiede** [comment]
I believe so

**Comment by vaindil** [comment]
Just a tip, it's very helpful if you include all relevant information in the PR description. I can figure out the basics, but it's helpful to know, for example, that the Discord token location changed in the config file. I figured it out pretty easily, but there are lots of people on GitHub who aren't so nice about things like that.

It looks like the log file is logging all messages that the bot receives, that's not the best idea for channels/servers that get a lot of traffic. Maybe move those to a verbose log level or make a toggle so they can be disabled?

It also looks like the config has changed a bit so that old versions of the bot won't automatically sync channels after this update. What's the update process for that? I can't upgrade the bots I'm running (either for prod or for testing) without knowing that.

**Comment by hbiede** [comment]
Apologies. I am new to this project and assumed the state of the system was up to date with the git repo when I was asked to make a PR here. I just copied all diffed files under that assumption

**Comment by hbiede** [comment]
As far as what the config should look like, it is formatted as the following on my end inside of memory.json:
```
"discord_relay_map": {
  "discord": {
    "CHANNEL_ID1": {
      "GHO_ID1": true
    },
    ...
  },
  "hangouts": {
    "GHO_ID1": {
      "CHANNEL_ID1": true
    },
    ...
  }
}
```

**Comment by vaindil** [comment]
Ah, okay. Is this just a courtesy merge or are you actively using this repo's code? My bots on this older version of upstream aren't exhibiting the duplicate message problem, they seem to be working fine. I can go through the work of getting up to date from upstream and then merge this PR if you'd like, but if you're not actually planning to use this repo then I'll probably decline the PR but pull your fork as a separate branch so I have a copy if that works for you.

Up to you, just let me know.

**Comment by hbiede** [comment]
I’m fine with whatever you want to do since clearly a lot of work has been done on our version of the code since last pull and I understand there would be a substantial amount of changes on your end.

**Comment by vaindil** [comment]
Sorry, I do appreciate the PR, but I'm going to close this and archive the repository. Thank you for your time!

**Pull request closed without merging**
